#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l pmem=12000mb
#PBS -l walltime=60:00:00
#PBS -d /storage/home/ssobie/code/repos/derived_gridded_indices/
#PBS -o /storage/home/ssobie/code/repos/derived_gridded_indices/sep.stdout.log
#PBS -e /storage/home/ssobie/code/repos/derived_gridded_indices/sep.stderr.log 

cd /storage/home/ssobie/code/repos/derived_gridded_indices/
echo "Current working directory is `pwd`"

module load R/3.2.5
module load netcdf-bin
module load cdo-bin
module load nco-bin

nohup R CMD BATCH --no-save --no-restore "--args tmpdir='/local_temp/ssobie/clim/' gcm='$gcm' scenario='$scenario' type='$type'" bcwide.climatologies.r "./${gcm}.${scenario}.${type}.clim.out"

