#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l pmem=10000mb
#PBS -l walltime=24:00:00
#PBS -d /storage/home/ssobie/code/repos/derived_gridded_indices/
#PBS -o /storage/home/ssobie/code/repos/derived_gridded_indices/cnr.derived.stdout.log
#PBS -e /storage/home/ssobie/code/repos/derived_gridded_indices/cnr.derived.stderr.log 
#PBS -N cnr_derv

gcm='CNRM-CM5'
scenario='rcp85'
run='r1i1p1'

cd /storage/home/ssobie/code/repos/derived_gridded_indices/
echo "Current working directory is `pwd`"

module load R/3.2.5
module load netcdf-bin
module load cdo-bin
module load nco-bin

nohup R CMD BATCH --no-save --no-restore "--args tmpdir='/local_temp/ssobie/prism/' gcm='$gcm' scenario='$scenario' run='$run'" cedar.derived.files.creation.r "./${gcm}.${scenario}.${run}.out"

