#!/bin/bash
#PBS -l nodes=worker-2.compute.pcic.uvic.ca:ppn=1
#PBS -l pmem=1000mb
#PBS -l walltime=01:00:00
#PBS -d /storage/home/ssobie/code/repos/derived_gridded_indices/
#PBS -o /storage/home/ssobie/code/repos/derived_gridded_indices/cleanup.stdout.log
#PBS -e /storage/home/ssobie/code/repos/derived_gridded_indices/cleanup.stderr.log 
#PBS -N clean

cd /storage/home/ssobie/code/repos/derived_gridded_indices/
echo "Current working directory is `pwd`"

module load R/3.2.5
module load netcdf-bin
module load cdo-bin
module load nco-bin

nohup R CMD BATCH --no-save --no-restore "--args tmpdir='/local_temp/ssobie/crcm5/'" clean.tmp.r "./clean.out"

