#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l pmem=8000mb
#PBS -l walltime=54:00:00
#PBS -d /storage/home/ssobie/code/repos/derived_gridded_indices/
#PBS -o /storage/home/ssobie/code/repos/derived_gridded_indices/daily.prism.stdout.log
#PBS -e /storage/home/ssobie/code/repos/derived_gridded_indices/daily.prism.stderr.log 

###gcm='CCSM4'
###scenario='rcp85'
###varname='pr'

cd /storage/home/ssobie/code/repos/derived_gridded_indices/
echo "Current working directory is `pwd`"

module load R/3.2.5
module load netcdf-bin
module load cdo-bin
module load nco-bin

nohup R CMD BATCH "--args tmpdir='/local_temp/ssobie/prism/' gcm='$gcm' scenario='$scenario' varname='$varname'" make.daily.prism.r "./${gcm}.${scenario}.${varname}.daily.prism.out"

