#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l pmem=10000mb
#PBS -l walltime=48:00:00
#PBS -d /storage/home/ssobie/code/repos/derived_gridded_indices/
#PBS -o /storage/home/ssobie/code/repos/derived_gridded_indices/rp.tn71.stdout.log
#PBS -e /storage/home/ssobie/code/repos/derived_gridded_indices/rp.tn71.stderr.log 
#PBS -N rp_tn_2071

gcm='All'
run='r1i1p1'

cd /storage/home/ssobie/code/repos/derived_gridded_indices/
echo "Current working directory is `pwd`"

module load R/3.2.5
module load netcdf-bin
module load cdo-bin
module load nco-bin

nohup R CMD BATCH "--args tmpdir='/local_temp/ssobie/rp/' gcm='$gcm' run='$run'" compute.rp.confidence.intervals.r "./${gcm}.rp71.tn.out"

