#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l pmem=10000mb
#PBS -l walltime=36:00:00
#PBS -d /storage/home/ssobie/code/repos/derived_gridded_indices/
#PBS -o /storage/home/ssobie/code/repos/derived_gridded_indices/mpi.clim.stdout.log
#PBS -e /storage/home/ssobie/code/repos/derived_gridded_indices/mpi.clim.stderr.log 
#PBS -N climdex_mpi

gcm='MPI-ESM-LR'
run='r3i1p1'

cd /storage/home/ssobie/code/repos/derived_gridded_indices/
echo "Current working directory is `pwd`"

module load R/3.2.5
module load netcdf-bin
module load cdo-bin
module load nco-bin

nohup R CMD BATCH "--args tmpdir='/local_temp/ssobie/climdex/' gcm='$gcm' run='$run'" compute.climdex.files.r "./${gcm}.climdex.out"

